name: Docs Build & Deployment

on: 
  push:
    branches: [docs]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('**/make.bat') }}
        restore-keys: |
          {{ runner.os }}-pip-
    - name: Install dependencies
      run: |
           python -m pip install --upgrade pip
           python -m pip install sphinx
           python -m pip install numpydoc  
           python -m pip install sphinx_mdinclude
           python -m pip install sphinx-rtd-theme
           python -m pip install sphinx-gallery
           python -m pip install nbsphinx-link
           python -m pip install nbsphinx
           python -m pip install sphinxcontrib-email
           python -m pip install ipython
           python -m pip install .
    - name: Setup Pandoc
      uses: r-lib/actions/setup-pandoc@v2
    - name: Build with Sphinx
      run: |
           sphinx-build -E -b html ./docs/source ./pages
    - name: Deploy to GH-Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./pages
